config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :orders
  resources :products
  resources :users

  resources :sites, only: [:edit, :update, :index]

  get 'mobile', to: 'welcome#mobile'
  root to: 'welcome#index'
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id          :bigint           not null, primary key
#  user_id     :integer
#  product_id  :string(255)
#  quantity    :integer
#  total_price :float(24)
#  address_id  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit]
  before_action :set_breadcrumb

  def index
    @q = current_user.orders.ransack params[:q]
    @orders = @q.result.order('id asc').page params[:page]
  end

  def show
  end


  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:user_id, :product_id, :quantity, :total_price, :address_id)

    end

    def set_breadcrumb
      @breadcrumb_list = [OpenStruct.new(name: "我的小店", path: root_path), OpenStruct.new(name: "全部订单", path: orders_path) ]
    end
end

app/views/orders/_form.html.haml
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      %ul
        - @order.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :user_id
    = f.number_field :user_id
  .field
    = f.label :product_id
    = f.text_field :product_id
  .field
    = f.label :quantity
    = f.number_field :quantity
  .field
    = f.label :total_price
    = f.text_field :total_price
  .field
    = f.label :address_id
    = f.number_field :address_id
  .actions
    = f.submit 'Save'

app/views/orders/_list.html.haml
%table.table
  %thead
    %th ID
    %th 产品
    %th 状态
    %th 数量
    %th 总价
    %th 电话
    %th 备注
  %tbody
    - orders.each do |order|
      %tr
        %td
          \#
          = link_to order.id, order_path(order)
        %td= order.product.name
        %td 未发货
        %td= order.user.email
        %td= order.quantity
        %td= order.total_price
        %td= order.created_at

= paginate orders

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

= link_to 'Show', @order
\|
= link_to 'Back', orders_path

app/views/orders/index.html.haml
-#= render :partial => "list", locals: { orders: @orders }

= box_helper "success" do
  = box_header_helper "我的订单", :server do
    .box-tools.pull-right
      -#= render :partial => "widgets/search_form", locals: { q: @q }
  = box_body_helper do
    = render :partial => "widgets/list_place_holder" if @orders.empty?
    - if @orders.present?
      = render :partial => "list", locals: { orders: @orders } 

app/views/orders/new.html.haml
%h1 New order

= render 'form'

= link_to 'Back', orders_path

app/views/orders/show.html.haml
%p#notice= notice

%p
  %b User:
  = @order.user_id
%p
  %b Product:
  = @order.product_id
%p
  %b Quantity:
  = @order.quantity
%p
  %b Total price:
  = @order.total_price
%p
  %b Address:
  = @order.address_id

= link_to 'Edit', edit_order_path(@order)
\|
= link_to 'Back', orders_path