config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :orders
  resources :products
  resources :users

  resources :sites, only: [:edit, :update, :index]

  get 'mobile', to: 'welcome#mobile'
  root to: 'welcome#index'
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id              :bigint           not null, primary key
#  name            :string(255)
#  user_id         :string(255)
#  desc            :text(65535)
#  short_desc      :text(65535)
#  state           :string(255)
#  price           :decimal(10, )
#  discount_price  :decimal(10, )
#  quantity        :integer
#  quantity_remain :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Product < ApplicationRecord
  STATES = {
    active: '售卖中',
    inactive: '编辑中',
    archived: '隐藏'
  }

  has_many :orders
  belongs_to :user

  validates :name, uniqueness: { scope: :user_id }
  validates :user_id, :price, :discount_price, :quantity_remain, :quantity,  presence: true
  validates :quantity, :quantity_remain, numericality: { gt: 0 }

  STATES.keys.each do |state|
    scope state, -> { where(state: state) }
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:update, :destroy]

  def index
    @q = current_user.products.ransack params[:q]
    @product = current_user.current_product || current_user.products.build
    @products = @q.result.order('id asc').page params[:page]
  end

  def show
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :user_id, :desc, :short_desc, :state)
    end
end

app/views/products/_form.html.haml
= simple_form_for product do |form|
  = box_body_helper do
    = form.input :name, label: '商品名称'
    = form.input :quantity, label: '数量'
    = form.input :quantity_remain, label: '剩余'
    = form.input :price, label: '价格'
    = form.input :discount_price, label: '折后价'
    = form.input :short_desc, as: :text, label: '商品描述'
    = form.input :desc, as: :text, label: '商品详情'
    = form.submit '保存', class: primary_btn_helper

app/views/products/edit.html.haml
= render 'form'

app/views/products/index.html.haml
.col-md-8
  = box_helper "success" do
    = box_header_helper "商品", :server do
      = render :partial => "form", locals: { product: @product }

.col-md-4
  = box_helper "success" do
    = box_body_helper do
      = render :partial => "widgets/list_place_holder" if @products.empty?
      - if @products.present?
        %table.table
          %thead
            %th ID
            %th 产品
          %tbody
            - @products.each do |product|
              %tr
                %td
                  \#
                  = link_to product.id, product_path(product)
                %td= product.name
          = paginate @products

  .phone-container.pull-right
    %iframe{src: mobile_path, frameborder: 0}

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @product.name
%p
  %b User:
  = @product.user_id
%p
  %b Desc:
  = @product.desc
%p
  %b Short desc:
  = @product.short_desc
%p
  %b State:
  = @product.state

= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path