config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  resources :orders
  resources :products
  resources :users

  resources :sites, only: [:edit, :update, :index]

  get 'mobile', to: 'welcome#mobile'
  root to: 'welcome#index'
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "发财"

    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"
    = yield :custom_assets

  %body{class: [controller_name, "skin-blue-light", "sidebar-mini"].join(" ") }
    .wrapper{style: 'min-height: 960px'}
      %header.main-header
        %a.logo{href: root_path}
          %span.logo-mini

          %span.logo-lg
            = "微商帮手"
        %nav.navbar.navbar-static-top
          %a.sidebar-toggle{role: 'button', data: {'toggle': 'push-menu' }}
            %span.sr-only
          .container-fluid
            %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar

            .navbar-collapse.collapse.navbar-responsive-collapse
              %ul.nav.navbar-nav.navbar-right
                %li{class: navbar_nav_active_class(:system) }= link_to "最新动态", root_path
                %li{class: navbar_nav_active_class(:system) }= link_to "帮助", root_path
                = drop_down fa_icon(:user) + " #{current_user.display}" do
                  = menu_item "设置", root_path
                  = menu_item "帮助", root_path
                  = menu_item "退出登录", destroy_user_session_path, method: :delete


      %aside.main-sidebar
        %section.sidebar
          %ul.sidebar-menu.tree{data: { widget: 'tree' }}
            %li.header 小店功能
            = sidebar_li_helper :dashboard, :home, "我的小店", root_path
            = sidebar_li_helper :orders, :bars, "全部订单", orders_path, false, {green: 2}
            = sidebar_li_helper :products, :server, "我的产品", products_path
            = sidebar_li_helper :users, :server, "全部买家", users_path
            - if current_user.site_admin?
              = sidebar_li_helper :sites, :server, '全部小站', sites_path
            %li.header 我的设置
            - if current_user.site_owner? and current_user.site
              = sidebar_li_helper :system, :gears, "店铺设置", edit_site_path(current_user.site), true

      .content-wrapper
        .content-header
          .margin-bottom
            = bootstrap_flash
          = render :partial => "widgets/breadcrumb"

        .content
          .row
            = yield

      %footer.main-footer
        %p &copy; Company 2019 (cming.xu@gmail.com)

app/views/layouts/mobile.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: 'width=device-width, initial-scale=1.0'}
    %title Lannister
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_pack_tag 'mobile'
  %body